# Homework 3

In [ ]:
By Yanhao Miao

1. Read the code below and rewrite it using only numpy functions (without for loop, if-else statements). Benchmark your implementation. How much is it faster than the naive python implementation? (hint: use np.isin)

In [3]:
def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx

In [21]:
import numpy as np

def func2(names, db):
    np_names = np.array(names)
    np_db = np.array(db)
    idx = np.arange(len(db))
    return idx[np.isin(np_db, np_names)]

In [22]:
# A simple test
names = list(range(1,100,3))
db = list(range(1,100,2))
print(func1(names, db))
print(func2(names, db))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [23]:
# Compare the time cost
names = list(range(1,10000,3))
db = list(range(1,100000,2))
%time func1(names, db)
%time func2(names, db)

CPU times: user 800 ms, sys: 2.25 ms, total: 802 ms
Wall time: 803 ms
CPU times: user 4.5 ms, sys: 444 µs, total: 4.94 ms
Wall time: 4.8 ms


array([   0,    3,    6, ..., 4992, 4995, 4998])

It's obvious that 'func2' is much more faster than the naive 'func1'.

2. Use only numpy functions (without for loop, if-else statements) to find the largest 3 distances between points if either points is inside the circle of raidus r0. Then return these points. E.g.

In [88]:
def search_pairs(coordinates, circle_r0):
    # calculate distance between pairs, into a symmetric matrix
    pair_dists = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates, axis=2)
    
    # obtains the points inside r0
    points_in_r0 = np.linalg.norm(coordinates, axis=1) < circle_r0
    
    # 'Either points is inside', so we use 'Xor'
    mask = points_in_r0[:, np.newaxis] ^ points_in_r0
    
    # we only need to consider the lower triangle, to obtain the largest 3 distances
    pair_dists = np.tril(pair_dists, k = -1)
    mask_lower = np.tril(np.ones_like(mask), k = -1)
    uniq_dists = pair_dists[mask & mask_lower]
    
    # get the three largest distances
    three_largest = np.partition(uniq_dists, -3)[-3:]
    # find the index
    index = np.where(np.isin(pair_dists, three_largest))
    return np.transpose(index)

In [87]:
coordinates = np.array(
[[0.968, 0.313],
 [0.692, 0.876],
 [0.895, 0.085],
 [0.039, 0.17 ],
 [0.878, 0.098]]
)
cirle_r0 = 0.9
print(search_pairs(coordinates, cirle_r0))

# The indices of the relevant points in the original coordinates

[[2 1]
 [3 0]
 [3 1]]
